import { Injectable } from '@nestjs/common';
import { InjectDataSource, InjectRepository } from '@nestjs/typeorm';
import { DataSource, Repository, IsNull } from 'typeorm';
import { SystemSettings } from './entities/system-settings.entity';
import { ActivityLog, ActivityType } from './entities/activity-log.entity';
import { UserSession } from './entities/user-session.entity';
import * as fs from 'fs';
import * as path from 'path';
import { exec } from 'child_process';
import { promisify } from 'util';
import * as XLSX from 'xlsx';

const execAsync = promisify(exec);

@Injectable()
export class AdminService {
  private serverStartTime: Date = new Date();

  constructor(
    @InjectDataSource()
    private dataSource: DataSource,
    @InjectRepository(SystemSettings)
    private settingsRepository: Repository<SystemSettings>,
    @InjectRepository(ActivityLog)
    private activityLogRepository: Repository<ActivityLog>,
    @InjectRepository(UserSession)
    private userSessionRepository: Repository<UserSession>,
  ) {}

  async createBackup(): Promise<string> {
    const backupId = `backup_${Date.now()}`;
    const backupDir = path.join(process.cwd(), 'backups');

    // 백업 디렉토리 생성
    if (!fs.existsSync(backupDir)) {
      fs.mkdirSync(backupDir, { recursive: true });
    }

    const backupPath = path.join(backupDir, `${backupId}.sql`);

    try {
      // PostgreSQL 연결 정보 가져오기
      const dbConfig = this.dataSource.options;

      // pg_dump 실행을 위한 환경변수 설정
      const env = {
        ...process.env,
        PGPASSWORD: dbConfig['password']?.toString() || '',
      };

      // pg_dump 명령어 실행 (spawn 사용으로 command injection 방지)
      const { spawn } = require('child_process');

      await new Promise<void>((resolve, reject) => {
        const pgDump = spawn('pg_dump', [
          '-h', String(dbConfig['host'] || 'localhost'),
          '-p', String(dbConfig['port'] || 5432),
          '-U', String(dbConfig['username']),
          '-d', String(dbConfig['database']),
          '-f', backupPath,
        ], { env });

        pgDump.on('close', (code) => {
          if (code === 0) {

            resolve();
          } else {
            reject(new Error(`pg_dump exited with code ${code}`));
          }
        });

        pgDump.on('error', (err) => {
          reject(err);
        });
      });

      // 활동 로그 기록
      await this.logActivity(
        ActivityType.BACKUP_CREATED,
        '백업 생성 완료',
        `백업 파일이 생성되었습니다: ${backupId}`,
        undefined, // 시스템 작업이므로 userId는 undefined
        { backupId, backupPath },
        'success',
      );

      return backupId;
    } catch (error) {

      // 실패 시 빈 SQL 파일 생성 (개발용)
      const mockBackup = `-- Mock backup created at ${new Date().toISOString()}
-- Database: ${this.dataSource.options['database']}
-- Generated by 42ERP Backup System

-- Users table backup would be here
-- Rooms table backup would be here
-- Reservations table backup would be here

SELECT 'Backup completed successfully' as status;
`;
      fs.writeFileSync(backupPath, mockBackup);
      return backupId;
    }
  }

  async getBackupFile(backupId: string): Promise<Buffer> {
    const backupDir = path.join(process.cwd(), 'backups');
    const backupPath = path.join(backupDir, `${backupId}.sql`);

    if (!fs.existsSync(backupPath)) {
      throw new Error('Backup file not found');
    }

    return fs.readFileSync(backupPath);
  }

  async deleteBackup(backupId: string): Promise<void> {
    const backupDir = path.join(process.cwd(), 'backups');
    const backupPath = path.join(backupDir, `${backupId}.sql`);

    if (fs.existsSync(backupPath)) {
      fs.unlinkSync(backupPath);
    }
  }

  async getBackupList(): Promise<any[]> {
    const backupDir = path.join(process.cwd(), 'backups');

    if (!fs.existsSync(backupDir)) {
      return [];
    }

    const files = fs.readdirSync(backupDir);
    const backups = files
      .filter((file) => file.endsWith('.sql'))
      .map((file) => {
        const filePath = path.join(backupDir, file);
        const stats = fs.statSync(filePath);
        const backupId = file.replace('.sql', '');

        return {
          id: backupId,
          name: backupId,
          type: backupId.includes('manual') ? 'manual' : 'auto',
          size: this.formatFileSize(stats.size),
          createdAt: stats.birthtime.toISOString(),
          status: 'completed',
          description: backupId.includes('manual') ? '수동 백업' : '자동 백업',
        };
      })
      .sort(
        (a, b) =>
          new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime(),
      );

    return backups;
  }

  async getBackupStats(): Promise<any> {
    const backupDir = path.join(process.cwd(), 'backups');

    if (!fs.existsSync(backupDir)) {
      return {
        totalSize: '0 MB',
        lastBackup: '없음',
      };
    }

    const files = fs.readdirSync(backupDir);
    const sqlFiles = files.filter((file) => file.endsWith('.sql'));

    if (sqlFiles.length === 0) {
      return {
        totalSize: '0 MB',
        lastBackup: '없음',
      };
    }

    // 총 크기 계산 및 생성 시간 수집
    let totalBytes = 0;
    const times: Date[] = [];

    sqlFiles.forEach((file) => {
      const filePath = path.join(backupDir, file);
      const stats = fs.statSync(filePath);
      totalBytes += stats.size;
      times.push(stats.birthtime);
    });

    // 가장 최근 백업 시간 찾기
    const latestTime = times.length > 0
      ? times.reduce((latest, current) => current > latest ? current : latest)
      : null;

    return {
      totalSize: this.formatFileSize(totalBytes),
      lastBackup: latestTime ? latestTime.toISOString() : '없음',
    };
  }

  async restoreBackup(backupId: string): Promise<void> {
    const backupDir = path.join(process.cwd(), 'backups');
    const backupPath = path.join(backupDir, `${backupId}.sql`);

    if (!fs.existsSync(backupPath)) {
      throw new Error('Backup file not found');
    }

    try {
      // PostgreSQL 연결 정보 가져오기
      const dbConfig = this.dataSource.options;

      // psql을 사용한 복원 (실제 운영환경에서는 주의 필요)
      const env = {
        ...process.env,
        PGPASSWORD: dbConfig['password']?.toString() || '',
      };

      const command = `psql -h ${dbConfig['host'] || 'localhost'} -p ${dbConfig['port'] || 5432} -U ${dbConfig['username']} -d ${dbConfig['database']} -f ${backupPath}`;

      await execAsync(command, { env });

    } catch (error) {

      throw new Error('Backup restoration failed');
    }
  }

  async getSystemStats(): Promise<any> {
    try {
      // 데이터베이스 통계 조회
      const userCount = await this.dataSource.query(
        'SELECT COUNT(*) FROM users',
      );
      const roomCount = await this.dataSource.query(
        'SELECT COUNT(*) FROM room',
      );
      const reservationCount = await this.dataSource.query(
        'SELECT COUNT(*) FROM reservation',
      );
      const todayReservationCount = await this.dataSource.query(
        `SELECT COUNT(*) FROM reservation WHERE DATE(reservation_createdat) = CURRENT_DATE`,
      );

      return {
        totalUsers: parseInt(userCount[0].count),
        totalRooms: parseInt(roomCount[0].count),
        totalReservations: parseInt(reservationCount[0].count),
        todayReservations: parseInt(todayReservationCount[0].count),
        systemUptime: process.uptime(),
        databaseSize: await this.getDatabaseSize(),
        lastBackup: await this.getLastBackupTime(),
      };
    } catch (error) {

      // 기본값 반환
      return {
        totalUsers: 0,
        totalRooms: 0,
        totalReservations: 0,
        todayReservations: 0,
        systemUptime: process.uptime(),
        databaseSize: 'Unknown',
        lastBackup: null,
      };
    }
  }

  private async getDatabaseSize(): Promise<string> {
    try {
      // current_database()를 사용하여 SQL Injection 방지
      const result = await this.dataSource.query(`
        SELECT pg_size_pretty(pg_database_size(current_database())) as size
      `);
      return result[0].size;
    } catch (error) {
      return 'Unknown';
    }
  }

  private async getLastBackupTime(): Promise<string | null> {
    const backupDir = path.join(process.cwd(), 'backups');

    if (!fs.existsSync(backupDir)) {
      return null;
    }

    const files = fs.readdirSync(backupDir);
    const sqlFiles = files.filter((file) => file.endsWith('.sql'));

    if (sqlFiles.length === 0) {
      return null;
    }

    const latestFile = sqlFiles
      .map((file) => ({
        file,
        time: fs.statSync(path.join(backupDir, file)).birthtime,
      }))
      .sort((a, b) => b.time.getTime() - a.time.getTime())[0];

    return latestFile.time.toISOString();
  }

  private formatFileSize(bytes: number): string {
    const sizes = ['Bytes', 'KB', 'MB', 'GB'];
    if (bytes === 0) return '0 Bytes';
    const i = Math.floor(Math.log(bytes) / Math.log(1024));
    return Math.round((bytes / Math.pow(1024, i)) * 100) / 100 + ' ' + sizes[i];
  }

  // 설정 관리 메서드들
  async getSettings(): Promise<any> {
    try {
      // 기본 설정값
      const defaultSettings = {
        reservation: {
          maxDaysAdvance: 30,
          maxDuration: 8,
          allowWeekends: false,
          requireApproval: true,
        },
        notifications: {
          emailEnabled: true,
          reminderHours: 24,
          adminNotifications: true,
          systemAlerts: true,
          slackWebhookUrl: '',
          slackEnabled: false,
        },
        security: {
          sessionTimeout: 60,
          maxLoginAttempts: 5,
          requireStrongPassword: true,
          twoFactorAuth: false,
        },
        system: {
          maintenanceMode: false,
          debugMode: false,
          backupRetentionDays: 30,
          logLevel: 'info',
        },
      };

      // 저장된 설정 조회
      const settingsRecords = await this.settingsRepository.find();
      const settings = { ...defaultSettings };

      // 저장된 설정으로 덮어쓰기
      settingsRecords.forEach((record) => {
        const keys = record.key.split('.');
        let current = settings;
        for (let i = 0; i < keys.length - 1; i++) {
          if (!current[keys[i]]) current[keys[i]] = {};
          current = current[keys[i]];
        }
        current[keys[keys.length - 1]] = record.value;
      });

      return settings;
    } catch (error) {

      // 에러 시 기본 설정 반환
      return {
        reservation: {
          maxDaysAdvance: 30,
          maxDuration: 8,
          allowWeekends: false,
          requireApproval: true,
        },
        notifications: {
          emailEnabled: true,
          reminderHours: 24,
          adminNotifications: true,
          systemAlerts: true,
          slackWebhookUrl: '',
          slackEnabled: false,
        },
        security: {
          sessionTimeout: 60,
          maxLoginAttempts: 5,
          requireStrongPassword: true,
          twoFactorAuth: false,
        },
        system: {
          maintenanceMode: false,
          debugMode: false,
          backupRetentionDays: 30,
          logLevel: 'info',
        },
      };
    }
  }

  async updateSettings(settings: any): Promise<void> {
    try {
      // 중첩된 객체를 플랫한 키-값 형태로 변환
      const flatSettings = this.flattenSettings(settings);

      // 각 설정을 개별적으로 저장 또는 업데이트
      for (const [key, value] of Object.entries(flatSettings)) {
        const existingSetting = await this.settingsRepository.findOne({
          where: { key },
        });

        if (existingSetting) {
          existingSetting.value = value;
          await this.settingsRepository.save(existingSetting);
        } else {
          const newSetting = this.settingsRepository.create({
            key,
            value,
            description: this.getSettingDescription(key),
          });
          await this.settingsRepository.save(newSetting);
        }
      }

      // 활동 로그 기록
      await this.logActivity(
        ActivityType.SETTINGS_UPDATED,
        '시스템 설정 업데이트',
        '시스템 설정이 업데이트되었습니다',
        undefined,
        { settingsKeys: Object.keys(flatSettings) },
        'success',
      );
    } catch (error) {

      throw error;
    }
  }

  async testSlackWebhook(webhookUrl: string): Promise<void> {
    try {
      const testMessage = {
        text: '🔔 *Slack 웹훅 테스트*',
        blocks: [
          {
            type: 'header',
            text: {
              type: 'plain_text',
              text: '🔔 Slack 웹훅 연동 테스트',
              emoji: true,
            },
          },
          {
            type: 'section',
            text: {
              type: 'mrkdwn',
              text: 'Slack 웹훅이 정상적으로 연동되었습니다!\n회의실 예약 신청 시 알림을 받을 수 있습니다.',
            },
          },
          {
            type: 'context',
            elements: [
              {
                type: 'mrkdwn',
                text: `테스트 시간: ${new Date().toLocaleString('ko-KR', { timeZone: 'Asia/Seoul' })}`,
              },
            ],
          },
        ],
      };

      const response = await fetch(webhookUrl, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify(testMessage),
      });

      if (!response.ok) {
        throw new Error(`Slack API returned ${response.status}: ${response.statusText}`);
      }

    } catch (error) {

      throw new Error(`Slack 웹훅 테스트 실패: ${error.message}`);
    }
  }

  async sendSlackNotification(
    webhookUrl: string,
    reservation: any,
  ): Promise<void> {
    try {
      const message = {
        text: '📅 새로운 회의실 예약 신청',
        blocks: [
          {
            type: 'header',
            text: {
              type: 'plain_text',
              text: '📅 새로운 회의실 예약 신청',
              emoji: true,
            },
          },
          {
            type: 'section',
            fields: [
              {
                type: 'mrkdwn',
                text: `*예약자:*\n${reservation.userName || reservation.username}`,
              },
              {
                type: 'mrkdwn',
                text: `*회의실:*\n${reservation.roomName}`,
              },
              {
                type: 'mrkdwn',
                text: `*시작 시간:*\n${new Date(reservation.startTime).toLocaleString('ko-KR', { timeZone: 'Asia/Seoul' })}`,
              },
              {
                type: 'mrkdwn',
                text: `*종료 시간:*\n${new Date(reservation.endTime).toLocaleString('ko-KR', { timeZone: 'Asia/Seoul' })}`,
              },
            ],
          },
          {
            type: 'section',
            text: {
              type: 'mrkdwn',
              text: `*목적:*\n${reservation.purpose || '미입력'}`,
            },
          },
          {
            type: 'context',
            elements: [
              {
                type: 'mrkdwn',
                text: `신청 시간: ${new Date().toLocaleString('ko-KR', { timeZone: 'Asia/Seoul' })}`,
              },
            ],
          },
        ],
      };

      const response = await fetch(webhookUrl, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify(message),
      });

      if (!response.ok) {
        throw new Error(`Slack API returned ${response.status}`);
      }

    } catch (error) {

      // Slack 알림 실패는 예약 생성을 막지 않음
    }
  }

  async setMaintenanceMode(enabled: boolean): Promise<void> {
    const existingSetting = await this.settingsRepository.findOne({
      where: { key: 'system.maintenanceMode' },
    });

    if (existingSetting) {
      existingSetting.value = enabled;
      await this.settingsRepository.save(existingSetting);
    } else {
      const newSetting = this.settingsRepository.create({
        key: 'system.maintenanceMode',
        value: enabled,
        description: '시스템 유지보수 모드 활성화 여부',
      });
      await this.settingsRepository.save(newSetting);
    }
  }

  private flattenSettings(obj: any, prefix = ''): Record<string, any> {
    const flattened = {};

    for (const key in obj) {
      if (obj.hasOwnProperty(key)) {
        const newKey = prefix ? `${prefix}.${key}` : key;

        if (
          typeof obj[key] === 'object' &&
          obj[key] !== null &&
          !Array.isArray(obj[key])
        ) {
          Object.assign(flattened, this.flattenSettings(obj[key], newKey));
        } else {
          flattened[newKey] = obj[key];
        }
      }
    }

    return flattened;
  }

  private getSettingDescription(key: string): string {
    const descriptions = {
      'reservation.maxDaysAdvance': '최대 사전 예약 가능 일수',
      'reservation.maxDuration': '최대 예약 시간(시간)',
      'reservation.allowWeekends': '주말 예약 허용 여부',
      'reservation.requireApproval': '관리자 승인 필수 여부',
      'notifications.emailEnabled': '이메일 알림 활성화',
      'notifications.reminderHours': '예약 알림 시간(시간 전)',
      'notifications.adminNotifications': '관리자 알림 활성화',
      'notifications.systemAlerts': '시스템 경고 알림 활성화',
      'security.sessionTimeout': '세션 타임아웃(분)',
      'security.maxLoginAttempts': '최대 로그인 시도 횟수',
      'security.requireStrongPassword': '강력한 비밀번호 요구',
      'security.twoFactorAuth': '2단계 인증 활성화',
      'system.maintenanceMode': '유지보수 모드',
      'system.debugMode': '디버그 모드',
      'system.backupRetentionDays': '백업 보관 기간(일)',
      'system.logLevel': '시스템 로그 레벨',
    };

    return descriptions[key] || '';
  }

  // 통계 관련 메서드들
  async getStatistics(period: string = '30d'): Promise<any> {
    const days = this.parsePeriodToDays(period);
    const startDate = new Date();
    startDate.setDate(startDate.getDate() - days);

    // 전체 통계
    const totalUsers = await this.dataSource.query(
      'SELECT COUNT(*) FROM users',
    );
    const totalRooms = await this.dataSource.query(
      'SELECT COUNT(*) FROM room',
    );
    const totalReservations = await this.dataSource.query(
      'SELECT COUNT(*) FROM reservation',
    );
    const activeReservations = await this.dataSource.query(
      `SELECT COUNT(*) FROM reservation WHERE reservation_starttime > NOW()`,
    );

    // 성장률 계산
    const userGrowth = await this.calculateGrowthRate('users', days);
    const reservationGrowth = await this.calculateGrowthRate(
      'reservation',
      days,
    );

    // 예약 상태별 통계
    const reservationsByStatus = await this.dataSource.query(
      `
      SELECT
        reservation_status as status,
        COUNT(*) as count
      FROM reservation
      WHERE reservation_createdat >= $1
      GROUP BY reservation_status
    `,
      [startDate],
    );

    const statusCounts = {
      confirmed: 0,
      cancelled: 0,
      completed: 0,
    };
    reservationsByStatus.forEach((r: any) => {
      if (r.status === 'confirmed') statusCounts.confirmed = parseInt(r.count);
      else if (r.status === 'cancelled') statusCounts.cancelled = parseInt(r.count);
      else if (r.status === 'finished') statusCounts.completed = parseInt(r.count);
    });

    // 월별 예약 추이
    const monthlyReservations = await this.dataSource.query(
      `
      SELECT
        TO_CHAR(reservation_createdat, 'YYYY-MM') as month,
        COUNT(*) as count
      FROM reservation
      WHERE reservation_createdat >= $1
      GROUP BY TO_CHAR(reservation_createdat, 'YYYY-MM')
      ORDER BY month DESC
      LIMIT 6
    `,
      [startDate],
    );

    // 회의실별 이용률
    const roomStats = await this.dataSource.query(
      `
      SELECT
        r.room_name as room_name,
        COUNT(res.reservation_id) as reservation_count,
        ROUND(COUNT(res.reservation_id) * 100.0 / GREATEST(1, $1), 2) as utilization
      FROM room r
      LEFT JOIN reservation res ON r.room_id = res.room_id
        AND res.reservation_createdat >= $2
      GROUP BY r.room_id, r.room_name
      ORDER BY reservation_count DESC
    `,
      [days, startDate],
    );

    // 시간대별 예약 현황
    const hourlyStats = await this.dataSource.query(
      `
      SELECT
        EXTRACT(HOUR FROM reservation_starttime) as hour,
        COUNT(*) as count
      FROM reservation
      WHERE reservation_createdat >= $1
      GROUP BY EXTRACT(HOUR FROM reservation_starttime)
      ORDER BY hour
    `,
      [startDate],
    );

    // 활발한 사용자
    const topUsers = await this.dataSource.query(
      `
      SELECT
        u.user_intra_id as login,
        u.user_intra_id as displayName,
        COUNT(r.reservation_id) as reservation_count
      FROM users u
      LEFT JOIN reservation r ON u.user_id = r.user_id
        AND r.reservation_createdat >= $1
      GROUP BY u.user_id, u.user_intra_id
      ORDER BY reservation_count DESC
      LIMIT 5
    `,
      [startDate],
    );

    // 사용자 등록 추이
    const userRegistrationTrend = await this.dataSource.query(
      `
      SELECT
        TO_CHAR(user_createdat, 'YYYY-MM') as month,
        COUNT(*) as count
      FROM users
      WHERE user_createdat >= $1
      GROUP BY TO_CHAR(user_createdat, 'YYYY-MM')
      ORDER BY month DESC
      LIMIT 6
    `,
      [startDate],
    );

    // 이번 달 신규 사용자 수
    const thisMonthStart = new Date();
    thisMonthStart.setDate(1);
    thisMonthStart.setHours(0, 0, 0, 0);
    const newUsersThisMonth = await this.dataSource.query(
      `SELECT COUNT(*) FROM users WHERE user_createdat >= $1`,
      [thisMonthStart],
    );

    // 시스템 통계 계산
    const systemStats = await this.calculateSystemStats(startDate);

    return {
      overview: {
        totalUsers: parseInt(totalUsers[0].count),
        totalRooms: parseInt(totalRooms[0].count),
        totalReservations: parseInt(totalReservations[0].count),
        activeReservations: parseInt(activeReservations[0].count),
        userGrowth: userGrowth,
        reservationGrowth: reservationGrowth,
      },
      reservationStats: {
        byStatus: statusCounts,
        byMonth: monthlyReservations.map((m) => ({
          month: this.formatMonth(m.month),
          count: parseInt(m.count),
          growth: 0,
        })),
        byRoom: roomStats.map((r) => ({
          roomName: r.room_name,
          count: parseInt(r.reservation_count),
          utilization: parseFloat(r.utilization),
        })),
        byHour: hourlyStats.map((h) => ({
          hour: parseInt(h.hour),
          count: parseInt(h.count),
        })),
      },
      userStats: {
        activeUsers: parseInt(totalUsers[0].count),
        newUsersThisMonth: parseInt(newUsersThisMonth[0].count),
        topUsers: topUsers.map((u) => ({
          login: u.login,
          displayName: u.displayName,
          reservationCount: parseInt(u.reservation_count),
        })),
        registrationTrend: userRegistrationTrend.map((u) => ({
          month: this.formatMonth(u.month),
          count: parseInt(u.count),
        })),
      },
      systemStats,
    };
  }

  async exportStatistics(): Promise<Buffer> {
    try {
      const statistics = await this.getStatistics('30d');

      // 전체 통계 시트
      const overviewData = [
        ['항목', '값'],
        ['총 사용자', statistics.overview.totalUsers],
        ['총 회의실', statistics.overview.totalRooms],
        ['총 예약', statistics.overview.totalReservations],
        ['활성 예약', statistics.overview.activeReservations],
        ['사용자 증가율', `${statistics.overview.userGrowth}%`],
        ['예약 증가율', `${statistics.overview.reservationGrowth}%`],
      ];

      // 회의실별 이용률 시트
      const roomData = [
        ['회의실명', '예약 수', '이용률(%)'],
        ...statistics.reservationStats.byRoom.map((room) => [
          room.roomName,
          room.count,
          room.utilization,
        ]),
      ];

      // 활발한 사용자 시트
      const usersData = [
        ['로그인 ID', '이름', '예약 수'],
        ...statistics.userStats.topUsers.map((user) => [
          user.login,
          user.displayName || '',
          user.reservationCount,
        ]),
      ];

      // 월별 예약 추이 시트
      const monthlyData = [
        ['월', '예약 수'],
        ...statistics.reservationStats.byMonth.map((month) => [
          month.month,
          month.count,
        ]),
      ];

      // 워크북 생성
      const workbook = XLSX.utils.book_new();

      // 시트 추가
      const overviewSheet = XLSX.utils.aoa_to_sheet(overviewData);
      const roomSheet = XLSX.utils.aoa_to_sheet(roomData);
      const usersSheet = XLSX.utils.aoa_to_sheet(usersData);
      const monthlySheet = XLSX.utils.aoa_to_sheet(monthlyData);

      XLSX.utils.book_append_sheet(workbook, overviewSheet, '전체 통계');
      XLSX.utils.book_append_sheet(workbook, roomSheet, '회의실별 이용률');
      XLSX.utils.book_append_sheet(workbook, usersSheet, '활발한 사용자');
      XLSX.utils.book_append_sheet(workbook, monthlySheet, '월별 예약 추이');

      return Buffer.from(
        XLSX.write(workbook, { type: 'buffer', bookType: 'xlsx' }),
      );
    } catch (error) {

      throw error;
    }
  }

  private parsePeriodToDays(period: string): number {
    switch (period) {
      case '7d':
        return 7;
      case '30d':
        return 30;
      case '90d':
        return 90;
      case '1y':
        return 365;
      default:
        return 30;
    }
  }

  private async calculateGrowthRate(
    table: string,
    days: number,
  ): Promise<number> {
    try {
      // Whitelist allowed tables to prevent SQL injection
      const allowedTables: { [key: string]: string } = {
        'users': 'user_createdat',
        'reservation': 'reservation_createdat',
      };

      if (!allowedTables[table]) {
        throw new Error(`Invalid table name: ${table}`);
      }

      const createdAtColumn = allowedTables[table];

      const currentPeriod = new Date();
      currentPeriod.setDate(currentPeriod.getDate() - days);

      const previousPeriod = new Date();
      previousPeriod.setDate(previousPeriod.getDate() - days * 2);

      const currentCount = await this.dataSource.query(
        `SELECT COUNT(*) FROM ${table} WHERE ${createdAtColumn} >= $1`,
        [currentPeriod],
      );

      const previousCount = await this.dataSource.query(
        `SELECT COUNT(*) FROM ${table} WHERE ${createdAtColumn} >= $1 AND ${createdAtColumn} < $2`,
        [previousPeriod, currentPeriod],
      );

      const current = parseInt(currentCount[0].count);
      const previous = parseInt(previousCount[0].count);

      if (previous === 0) return current > 0 ? 100 : 0;
      return Math.round(((current - previous) / previous) * 100 * 100) / 100;
    } catch (error) {

      return 0;
    }
  }

  private formatMonth(monthStr: string): string {
    const [year, month] = monthStr.split('-');
    return `${parseInt(month)}월`;
  }

  // ========== 세션 추적 시스템 ==========

  /**
   * 사용자 로그인 시 세션 생성
   */
  async createSession(
    userId: number,
    ipAddress?: string,
    userAgent?: string,
  ): Promise<UserSession> {
    // 기존 활성 세션 종료
    await this.endActiveSessions(userId);

    const session = this.userSessionRepository.create({
      userId,
      ipAddress: ipAddress || null,
      userAgent: userAgent || null,
      isActive: true,
    });

    return await this.userSessionRepository.save(session);
  }

  /**
   * 사용자 로그아웃 시 세션 종료
   */
  async endSession(userId: number): Promise<void> {
    const activeSessions = await this.userSessionRepository.find({
      where: { userId, isActive: true },
    });

    const now = new Date();
    for (const session of activeSessions) {
      session.logoutAt = now;
      session.isActive = false;
      session.durationMinutes = Math.round(
        (now.getTime() - session.loginAt.getTime()) / (1000 * 60),
      );
      await this.userSessionRepository.save(session);
    }
  }

  /**
   * 사용자의 모든 활성 세션 종료
   */
  private async endActiveSessions(userId: number): Promise<void> {
    await this.endSession(userId);
  }

  /**
   * 시스템 통계 계산 (세션 기반)
   */
  private async calculateSystemStats(startDate: Date): Promise<{
    averageSessionDuration: number;
    peakUsageHour: number;
    systemUptime: number;
    errorRate: number;
  }> {
    // 평균 세션 시간 계산
    const avgDurationResult = await this.dataSource.query(
      `
      SELECT COALESCE(AVG(duration_minutes), 0) as avg_duration
      FROM user_sessions
      WHERE login_at >= $1 AND duration_minutes IS NOT NULL
    `,
      [startDate],
    );
    const averageSessionDuration = Math.round(
      parseFloat(avgDurationResult[0]?.avg_duration || '0'),
    );

    // 피크 사용 시간대 계산 (로그인 기준)
    const peakHourResult = await this.dataSource.query(
      `
      SELECT EXTRACT(HOUR FROM login_at) as hour, COUNT(*) as count
      FROM user_sessions
      WHERE login_at >= $1
      GROUP BY EXTRACT(HOUR FROM login_at)
      ORDER BY count DESC
      LIMIT 1
    `,
      [startDate],
    );
    const peakUsageHour = peakHourResult[0]
      ? parseInt(peakHourResult[0].hour)
      : 14;

    // 시스템 가동률 계산 (서버 시작 시간 기준)
    const uptimeMs = Date.now() - this.serverStartTime.getTime();
    const totalPeriodMs = Date.now() - startDate.getTime();
    const systemUptime = Math.min(
      100,
      Math.round((uptimeMs / totalPeriodMs) * 100 * 100) / 100,
    );

    // 에러율 계산 (activity_logs에서 error 레벨 비율)
    const errorRateResult = await this.dataSource.query(
      `
      SELECT
        COUNT(*) FILTER (WHERE level = 'error') as error_count,
        COUNT(*) as total_count
      FROM activity_logs
      WHERE "createdAt" >= $1
    `,
      [startDate],
    );
    const errorCount = parseInt(errorRateResult[0]?.error_count || '0');
    const totalLogs = parseInt(errorRateResult[0]?.total_count || '1');
    const errorRate =
      totalLogs > 0
        ? Math.round((errorCount / totalLogs) * 100 * 100) / 100
        : 0;

    return {
      averageSessionDuration,
      peakUsageHour,
      systemUptime,
      errorRate,
    };
  }

  /**
   * 현재 활성 세션 수 조회
   */
  async getActiveSessionCount(): Promise<number> {
    const result = await this.userSessionRepository.count({
      where: { isActive: true },
    });
    return result;
  }

  /**
   * 특정 사용자의 세션 이력 조회
   */
  async getUserSessions(userId: number, limit: number = 10): Promise<UserSession[]> {
    return await this.userSessionRepository.find({
      where: { userId },
      order: { loginAt: 'DESC' },
      take: limit,
    });
  }

  // ========== 위험한 시스템 작업들 ==========
  async resetDatabase(): Promise<void> {

    // 실제 운영환경에서는 이 기능을 비활성화하거나 추가 보안 검증을 해야 합니다
    if (process.env.NODE_ENV === 'production') {
      throw new Error(
        'Database reset is not allowed in production environment',
      );
    }

    try {
      // 모든 테이블의 데이터를 삭제 (구조는 유지)
      await this.dataSource.query(
        'TRUNCATE TABLE reservation RESTART IDENTITY CASCADE',
      );
      await this.dataSource.query(
        'TRUNCATE TABLE room RESTART IDENTITY CASCADE',
      );
      await this.dataSource.query(
        'TRUNCATE TABLE users RESTART IDENTITY CASCADE',
      );
      await this.dataSource.query(
        'TRUNCATE TABLE system_settings RESTART IDENTITY CASCADE',
      );

    } catch (error) {

      throw new Error('Failed to reset database: ' + error.message);
    }
  }

  async clearLogs(): Promise<void> {

    try {
      const fs = require('fs');
      const path = require('path');

      // 로그 디렉토리 경로들
      const logPaths = [
        path.join(process.cwd(), 'logs'),
        path.join(process.cwd(), 'log.txt'),
        '/var/log/42erp', // 시스템 로그 경로 (실제 환경에 맞게 조정)
      ];

      for (const logPath of logPaths) {
        try {
          if (fs.existsSync(logPath)) {
            const stat = fs.statSync(logPath);

            if (stat.isDirectory()) {
              // 디렉토리인 경우 모든 파일 삭제
              const files = fs.readdirSync(logPath);
              for (const file of files) {
                const filePath = path.join(logPath, file);
                fs.unlinkSync(filePath);

              }
            } else {
              // 파일인 경우 직접 삭제
              fs.unlinkSync(logPath);

            }
          }
        } catch (error) {

        }
      }

    } catch (error) {

      throw new Error('Failed to clear logs: ' + error.message);
    }
  }

  async testApiKeys(): Promise<any> {

    const results = {
      api42: false,
      email: false,
    };

    try {
      // 42 API 테스트
      const clientId = process.env.FORTYTWO_CLIENT_ID;
      const clientSecret = process.env.FORTYTWO_CLIENT_SECRET;

      if (clientId && clientSecret) {
        // 간단한 42 API 연결 테스트 (토큰 없이 public endpoint 호출)
        try {
          const response = await fetch('https://api.intra.42.fr/oauth/token', {
            method: 'POST',
            headers: {
              'Content-Type': 'application/json',
            },
            body: JSON.stringify({
              grant_type: 'client_credentials',
              client_id: clientId,
              client_secret: clientSecret,
            }),
          });

          if (response.status === 200) {
            results.api42 = true;

          } else {

          }
        } catch (error) {

        }
      } else {

      }

      // 이메일 API 테스트 (SMTP 또는 SendGrid)
      const emailApiKey = process.env.EMAIL_API_KEY;
      const smtpHost = process.env.SMTP_HOST;

      if (emailApiKey || smtpHost) {
        // 실제 이메일 발송 없이 설정 유효성만 검증
        try {
          // 이메일 설정이 있다고 가정하고 true로 설정
          // 실제 환경에서는 SMTP 연결 테스트나 API 호출을 수행
          results.email = true;

        } catch (error) {

        }
      } else {

      }
    } catch (error) {

    }

    return results;
  }

  // 활동 로그 관련 메서드들
  async logActivity(
    type: ActivityType,
    title: string,
    description?: string,
    userId?: number,
    metadata?: any,
    level: 'info' | 'success' | 'warning' | 'error' = 'info',
  ): Promise<void> {
    try {
      const activityLog = this.activityLogRepository.create({
        type,
        title,
        description,
        userId,
        metadata,
        level,
      });
      await this.activityLogRepository.save(activityLog);
    } catch (error) {

    }
  }

  async getRecentActivities(limit: number = 10): Promise<ActivityLog[]> {
    try {
      return await this.activityLogRepository.find({
        relations: ['user'],
        order: { createdAt: 'DESC' },
        take: limit,
      });
    } catch (error) {

      return [];
    }
  }

  async getActivitiesByType(
    type: ActivityType,
    limit: number = 10,
  ): Promise<ActivityLog[]> {
    try {
      return await this.activityLogRepository.find({
        where: { type },
        relations: ['user'],
        order: { createdAt: 'DESC' },
        take: limit,
      });
    } catch (error) {

      return [];
    }
  }

  async clearOldActivities(daysOld: number = 30): Promise<void> {
    try {
      const cutoffDate = new Date();
      cutoffDate.setDate(cutoffDate.getDate() - daysOld);

      await this.activityLogRepository
        .createQueryBuilder()
        .delete()
        .where('createdAt < :cutoffDate', { cutoffDate })
        .execute();

    } catch (error) {

    }
  }

  async createSampleActivities(): Promise<void> {
    try {
      const now = new Date();

      const sampleActivities = [
        {
          type: ActivityType.ROOM_CREATED,
          title: '새 회의실 추가됨',
          description: "관리자에 의해 '대회의실 C' 추가",
          level: 'success' as const,
          createdAt: new Date(now.getTime() - 5 * 60 * 1000), // 5분 전
        },
        {
          type: ActivityType.EXCEL_UPLOAD,
          title: 'Excel 데이터 업로드',
          description: '15개 회의실 정보 일괄 업데이트',
          level: 'info' as const,
          createdAt: new Date(now.getTime() - 60 * 60 * 1000), // 1시간 전
        },
        {
          type: ActivityType.BACKUP_CREATED,
          title: '시스템 백업 완료',
          description: '자동 백업이 성공적으로 완료됨',
          level: 'success' as const,
          createdAt: new Date(now.getTime() - 3 * 60 * 60 * 1000), // 3시간 전
        },
        {
          type: ActivityType.USER_REGISTERED,
          title: '새 사용자 등록',
          description: '새로운 사용자가 시스템에 등록되었습니다',
          level: 'info' as const,
          createdAt: new Date(now.getTime() - 6 * 60 * 60 * 1000), // 6시간 전
        },
        {
          type: ActivityType.SETTINGS_UPDATED,
          title: '시스템 설정 변경',
          description: '예약 정책이 업데이트되었습니다',
          level: 'info' as const,
          createdAt: new Date(now.getTime() - 12 * 60 * 60 * 1000), // 12시간 전
        },
      ];

      for (const activity of sampleActivities) {
        // 중복 방지를 위해 기존 활동 확인
        const existing = await this.activityLogRepository.findOne({
          where: {
            title: activity.title,
            description: activity.description,
          },
        });

        if (!existing) {
          const activityLog = this.activityLogRepository.create(activity);
          await this.activityLogRepository.save(activityLog);
        }
      }

    } catch (error) {

    }
  }

  /**
   * 오래된 백업 파일 삭제
   * @param retentionDays 보관 기간 (일)
   */
  async cleanupOldBackups(retentionDays: number): Promise<number> {
    const backupDir = path.join(process.cwd(), 'backups');

    if (!fs.existsSync(backupDir)) {
      return 0;
    }

    const files = fs.readdirSync(backupDir);
    const sqlFiles = files.filter((file) => file.endsWith('.sql'));

    const cutoffDate = new Date();
    cutoffDate.setDate(cutoffDate.getDate() - retentionDays);

    let deletedCount = 0;

    for (const file of sqlFiles) {
      const filePath = path.join(backupDir, file);
      const stats = fs.statSync(filePath);

      if (stats.birthtime < cutoffDate) {
        fs.unlinkSync(filePath);
        deletedCount++;

      }
    }

    // 활동 로그 기록
    if (deletedCount > 0) {
      await this.logActivity(
        ActivityType.BACKUP_CREATED,
        '오래된 백업 정리',
        `${deletedCount}개의 오래된 백업 파일이 삭제되었습니다`,
        undefined,
        { deletedCount, retentionDays },
        'info',
      );
    }

    return deletedCount;
  }

  /**
   * 백업 스케줄 상태 조회
   */
  async getBackupScheduleStatus(): Promise<any> {
    const settings = await this.getSettings();
    const backupHour = settings.system?.backupHour || 2;

    return {
      enabled: settings.system?.backupEnabled !== false, // 자동 백업 활성화 여부 (기본값: true)
      schedule: this.formatBackupSchedule(backupHour),
      backupHour: backupHour,
      retentionDays: settings.system?.backupRetentionDays || 30,
      lastBackup: await this.getLastBackupTime(),
      nextBackup: this.getNextBackupTime(backupHour),
    };
  }

  /**
   * 백업 스케줄 포맷팅
   */
  private formatBackupSchedule(hour: number): string {
    const period = hour < 12 ? '오전' : '오후';
    const displayHour = hour === 0 ? 12 : hour > 12 ? hour - 12 : hour;
    return `매일 ${period} ${displayHour}시`;
  }

  /**
   * 백업 스케줄 설정 업데이트
   */
  async updateBackupSchedule(enabled: boolean, retentionDays: number, backupHour?: number): Promise<void> {
    try {
      // 백업 활성화 상태 업데이트
      const enabledSetting = await this.settingsRepository.findOne({
        where: { key: 'system.backupEnabled' },
      });

      if (enabledSetting) {
        enabledSetting.value = enabled;
        await this.settingsRepository.save(enabledSetting);
      } else {
        const newSetting = this.settingsRepository.create({
          key: 'system.backupEnabled',
          value: enabled,
          description: '자동 백업 활성화 여부',
        });
        await this.settingsRepository.save(newSetting);
      }

      // 백업 보관 기간 업데이트
      const retentionSetting = await this.settingsRepository.findOne({
        where: { key: 'system.backupRetentionDays' },
      });

      if (retentionSetting) {
        retentionSetting.value = retentionDays;
        await this.settingsRepository.save(retentionSetting);
      } else {
        const newSetting = this.settingsRepository.create({
          key: 'system.backupRetentionDays',
          value: retentionDays,
          description: '백업 보관 기간 (일)',
        });
        await this.settingsRepository.save(newSetting);
      }

      // 백업 시간 업데이트
      if (backupHour !== undefined) {
        const hourSetting = await this.settingsRepository.findOne({
          where: { key: 'system.backupHour' },
        });

        if (hourSetting) {
          hourSetting.value = backupHour;
          await this.settingsRepository.save(hourSetting);
        } else {
          const newSetting = this.settingsRepository.create({
            key: 'system.backupHour',
            value: backupHour,
            description: '자동 백업 실행 시간 (0-23)',
          });
          await this.settingsRepository.save(newSetting);
        }
      }

      // 활동 로그 기록
      await this.logActivity(
        ActivityType.SETTINGS_UPDATED,
        '백업 스케줄 설정 변경',
        `자동 백업: ${enabled ? '활성화' : '비활성화'}, 보관 기간: ${retentionDays}일${backupHour !== undefined ? `, 백업 시간: ${backupHour}시` : ''}`,
        undefined,
        { enabled, retentionDays, backupHour },
        'info',
      );

    } catch (error) {

      throw error;
    }
  }

  /**
   * 다음 백업 예정 시간 계산
   */
  private getNextBackupTime(backupHour: number = 2): string {
    const now = new Date();
    const next = new Date(now);

    // 지정된 시간으로 설정
    next.setHours(backupHour, 0, 0, 0);

    // 현재 시간이 백업 시간 이후라면 다음 날로 설정
    if (now.getHours() >= backupHour) {
      next.setDate(next.getDate() + 1);
    }

    return next.toISOString();
  }

}
