import { Injectable } from '@nestjs/common';
import { InjectDataSource, InjectRepository } from '@nestjs/typeorm';
import { DataSource, Repository } from 'typeorm';
import { SystemSettings } from './entities/system-settings.entity';
import { ActivityLog, ActivityType } from './entities/activity-log.entity';
import * as fs from 'fs';
import * as path from 'path';
import { exec } from 'child_process';
import { promisify } from 'util';
import * as XLSX from 'xlsx';

const execAsync = promisify(exec);

@Injectable()
export class AdminService {
  constructor(
    @InjectDataSource()
    private dataSource: DataSource,
    @InjectRepository(SystemSettings)
    private settingsRepository: Repository<SystemSettings>,
    @InjectRepository(ActivityLog)
    private activityLogRepository: Repository<ActivityLog>,
  ) {}

  async createBackup(): Promise<string> {
    const backupId = `backup_${Date.now()}`;
    const backupDir = path.join(process.cwd(), 'backups');

    // 백업 디렉토리 생성
    if (!fs.existsSync(backupDir)) {
      fs.mkdirSync(backupDir, { recursive: true });
    }

    const backupPath = path.join(backupDir, `${backupId}.sql`);

    try {
      // PostgreSQL 연결 정보 가져오기
      const dbConfig = this.dataSource.options;

      // pg_dump 실행을 위한 환경변수 설정
      const env = {
        ...process.env,
        PGPASSWORD: dbConfig['password']?.toString() || '',
      };

      // pg_dump 명령어 실행 (spawn 사용으로 command injection 방지)
      const { spawn } = require('child_process');

      await new Promise<void>((resolve, reject) => {
        const pgDump = spawn('pg_dump', [
          '-h', String(dbConfig['host'] || 'localhost'),
          '-p', String(dbConfig['port'] || 5432),
          '-U', String(dbConfig['username']),
          '-d', String(dbConfig['database']),
          '-f', backupPath,
        ], { env });

        pgDump.on('close', (code) => {
          if (code === 0) {
            console.log('Backup created successfully:', backupPath);
            resolve();
          } else {
            reject(new Error(`pg_dump exited with code ${code}`));
          }
        });

        pgDump.on('error', (err) => {
          reject(err);
        });
      });

      // 활동 로그 기록
      await this.logActivity(
        ActivityType.BACKUP_CREATED,
        '백업 생성 완료',
        `백업 파일이 생성되었습니다: ${backupId}`,
        undefined, // 시스템 작업이므로 userId는 undefined
        { backupId, backupPath },
        'success',
      );

      return backupId;
    } catch (error) {
      console.error('Backup creation failed:', error);
      // 실패 시 빈 SQL 파일 생성 (개발용)
      const mockBackup = `-- Mock backup created at ${new Date().toISOString()}
-- Database: ${this.dataSource.options['database']}
-- Generated by 42ERP Backup System

-- Users table backup would be here
-- Rooms table backup would be here
-- Reservations table backup would be here

SELECT 'Backup completed successfully' as status;
`;
      fs.writeFileSync(backupPath, mockBackup);
      return backupId;
    }
  }

  async getBackupFile(backupId: string): Promise<Buffer> {
    const backupDir = path.join(process.cwd(), 'backups');
    const backupPath = path.join(backupDir, `${backupId}.sql`);

    if (!fs.existsSync(backupPath)) {
      throw new Error('Backup file not found');
    }

    return fs.readFileSync(backupPath);
  }

  async deleteBackup(backupId: string): Promise<void> {
    const backupDir = path.join(process.cwd(), 'backups');
    const backupPath = path.join(backupDir, `${backupId}.sql`);

    if (fs.existsSync(backupPath)) {
      fs.unlinkSync(backupPath);
    }
  }

  async getBackupList(): Promise<any[]> {
    const backupDir = path.join(process.cwd(), 'backups');

    if (!fs.existsSync(backupDir)) {
      return [];
    }

    const files = fs.readdirSync(backupDir);
    const backups = files
      .filter((file) => file.endsWith('.sql'))
      .map((file) => {
        const filePath = path.join(backupDir, file);
        const stats = fs.statSync(filePath);
        const backupId = file.replace('.sql', '');

        return {
          id: backupId,
          name: backupId,
          type: backupId.includes('manual') ? 'manual' : 'auto',
          size: this.formatFileSize(stats.size),
          createdAt: stats.birthtime.toISOString(),
          status: 'completed',
          description: backupId.includes('manual') ? '수동 백업' : '자동 백업',
        };
      })
      .sort(
        (a, b) =>
          new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime(),
      );

    return backups;
  }

  async restoreBackup(backupId: string): Promise<void> {
    const backupDir = path.join(process.cwd(), 'backups');
    const backupPath = path.join(backupDir, `${backupId}.sql`);

    if (!fs.existsSync(backupPath)) {
      throw new Error('Backup file not found');
    }

    try {
      // PostgreSQL 연결 정보 가져오기
      const dbConfig = this.dataSource.options;

      // psql을 사용한 복원 (실제 운영환경에서는 주의 필요)
      const env = {
        ...process.env,
        PGPASSWORD: dbConfig['password']?.toString() || '',
      };

      const command = `psql -h ${dbConfig['host'] || 'localhost'} -p ${dbConfig['port'] || 5432} -U ${dbConfig['username']} -d ${dbConfig['database']} -f ${backupPath}`;

      console.log('Restoring backup with command:', command);
      await execAsync(command, { env });

      console.log('Backup restored successfully');
    } catch (error) {
      console.error('Backup restoration failed:', error);
      throw new Error('Backup restoration failed');
    }
  }

  async getSystemStats(): Promise<any> {
    try {
      // 데이터베이스 통계 조회
      const userCount = await this.dataSource.query(
        'SELECT COUNT(*) FROM users',
      );
      const roomCount = await this.dataSource.query(
        'SELECT COUNT(*) FROM room',
      );
      const reservationCount = await this.dataSource.query(
        'SELECT COUNT(*) FROM reservation',
      );
      const todayReservationCount = await this.dataSource.query(
        `SELECT COUNT(*) FROM reservation WHERE DATE(reservation_createdat) = CURRENT_DATE`,
      );

      return {
        totalUsers: parseInt(userCount[0].count),
        totalRooms: parseInt(roomCount[0].count),
        totalReservations: parseInt(reservationCount[0].count),
        todayReservations: parseInt(todayReservationCount[0].count),
        systemUptime: process.uptime(),
        databaseSize: await this.getDatabaseSize(),
        lastBackup: await this.getLastBackupTime(),
      };
    } catch (error) {
      console.error('Failed to get system stats:', error);
      // 기본값 반환
      return {
        totalUsers: 0,
        totalRooms: 0,
        totalReservations: 0,
        todayReservations: 0,
        systemUptime: process.uptime(),
        databaseSize: 'Unknown',
        lastBackup: null,
      };
    }
  }

  private async getDatabaseSize(): Promise<string> {
    try {
      // current_database()를 사용하여 SQL Injection 방지
      const result = await this.dataSource.query(`
        SELECT pg_size_pretty(pg_database_size(current_database())) as size
      `);
      return result[0].size;
    } catch (error) {
      return 'Unknown';
    }
  }

  private async getLastBackupTime(): Promise<string | null> {
    const backupDir = path.join(process.cwd(), 'backups');

    if (!fs.existsSync(backupDir)) {
      return null;
    }

    const files = fs.readdirSync(backupDir);
    const sqlFiles = files.filter((file) => file.endsWith('.sql'));

    if (sqlFiles.length === 0) {
      return null;
    }

    const latestFile = sqlFiles
      .map((file) => ({
        file,
        time: fs.statSync(path.join(backupDir, file)).birthtime,
      }))
      .sort((a, b) => b.time.getTime() - a.time.getTime())[0];

    return latestFile.time.toISOString();
  }

  private formatFileSize(bytes: number): string {
    const sizes = ['Bytes', 'KB', 'MB', 'GB'];
    if (bytes === 0) return '0 Bytes';
    const i = Math.floor(Math.log(bytes) / Math.log(1024));
    return Math.round((bytes / Math.pow(1024, i)) * 100) / 100 + ' ' + sizes[i];
  }

  // 설정 관리 메서드들
  async getSettings(): Promise<any> {
    try {
      // 기본 설정값
      const defaultSettings = {
        reservation: {
          maxDaysAdvance: 30,
          maxDuration: 8,
          allowWeekends: false,
          requireApproval: true,
        },
        notifications: {
          emailEnabled: true,
          reminderHours: 24,
          adminNotifications: true,
          systemAlerts: true,
        },
        security: {
          sessionTimeout: 60,
          maxLoginAttempts: 5,
          requireStrongPassword: true,
          twoFactorAuth: false,
        },
        system: {
          maintenanceMode: false,
          debugMode: false,
          backupRetentionDays: 30,
          logLevel: 'info',
        },
      };

      // 저장된 설정 조회
      const settingsRecords = await this.settingsRepository.find();
      const settings = { ...defaultSettings };

      // 저장된 설정으로 덮어쓰기
      settingsRecords.forEach((record) => {
        const keys = record.key.split('.');
        let current = settings;
        for (let i = 0; i < keys.length - 1; i++) {
          if (!current[keys[i]]) current[keys[i]] = {};
          current = current[keys[i]];
        }
        current[keys[keys.length - 1]] = record.value;
      });

      return settings;
    } catch (error) {
      console.error('Failed to get settings:', error);
      // 에러 시 기본 설정 반환
      return {
        reservation: {
          maxDaysAdvance: 30,
          maxDuration: 8,
          allowWeekends: false,
          requireApproval: true,
        },
        notifications: {
          emailEnabled: true,
          reminderHours: 24,
          adminNotifications: true,
          systemAlerts: true,
        },
        security: {
          sessionTimeout: 60,
          maxLoginAttempts: 5,
          requireStrongPassword: true,
          twoFactorAuth: false,
        },
        system: {
          maintenanceMode: false,
          debugMode: false,
          backupRetentionDays: 30,
          logLevel: 'info',
        },
      };
    }
  }

  async updateSettings(settings: any): Promise<void> {
    try {
      // 중첩된 객체를 플랫한 키-값 형태로 변환
      const flatSettings = this.flattenSettings(settings);

      // 각 설정을 개별적으로 저장 또는 업데이트
      for (const [key, value] of Object.entries(flatSettings)) {
        const existingSetting = await this.settingsRepository.findOne({
          where: { key },
        });

        if (existingSetting) {
          existingSetting.value = value;
          await this.settingsRepository.save(existingSetting);
        } else {
          const newSetting = this.settingsRepository.create({
            key,
            value,
            description: this.getSettingDescription(key),
          });
          await this.settingsRepository.save(newSetting);
        }
      }

      console.log('Settings updated successfully');

      // 활동 로그 기록
      await this.logActivity(
        ActivityType.SETTINGS_UPDATED,
        '시스템 설정 업데이트',
        '시스템 설정이 업데이트되었습니다',
        undefined,
        { settingsKeys: Object.keys(flatSettings) },
        'success',
      );
    } catch (error) {
      console.error('Failed to update settings:', error);
      throw error;
    }
  }

  async setMaintenanceMode(enabled: boolean): Promise<void> {
    const existingSetting = await this.settingsRepository.findOne({
      where: { key: 'system.maintenanceMode' },
    });

    if (existingSetting) {
      existingSetting.value = enabled;
      await this.settingsRepository.save(existingSetting);
    } else {
      const newSetting = this.settingsRepository.create({
        key: 'system.maintenanceMode',
        value: enabled,
        description: '시스템 유지보수 모드 활성화 여부',
      });
      await this.settingsRepository.save(newSetting);
    }
  }

  private flattenSettings(obj: any, prefix = ''): Record<string, any> {
    const flattened = {};

    for (const key in obj) {
      if (obj.hasOwnProperty(key)) {
        const newKey = prefix ? `${prefix}.${key}` : key;

        if (
          typeof obj[key] === 'object' &&
          obj[key] !== null &&
          !Array.isArray(obj[key])
        ) {
          Object.assign(flattened, this.flattenSettings(obj[key], newKey));
        } else {
          flattened[newKey] = obj[key];
        }
      }
    }

    return flattened;
  }

  private getSettingDescription(key: string): string {
    const descriptions = {
      'reservation.maxDaysAdvance': '최대 사전 예약 가능 일수',
      'reservation.maxDuration': '최대 예약 시간(시간)',
      'reservation.allowWeekends': '주말 예약 허용 여부',
      'reservation.requireApproval': '관리자 승인 필수 여부',
      'notifications.emailEnabled': '이메일 알림 활성화',
      'notifications.reminderHours': '예약 알림 시간(시간 전)',
      'notifications.adminNotifications': '관리자 알림 활성화',
      'notifications.systemAlerts': '시스템 경고 알림 활성화',
      'security.sessionTimeout': '세션 타임아웃(분)',
      'security.maxLoginAttempts': '최대 로그인 시도 횟수',
      'security.requireStrongPassword': '강력한 비밀번호 요구',
      'security.twoFactorAuth': '2단계 인증 활성화',
      'system.maintenanceMode': '유지보수 모드',
      'system.debugMode': '디버그 모드',
      'system.backupRetentionDays': '백업 보관 기간(일)',
      'system.logLevel': '시스템 로그 레벨',
    };

    return descriptions[key] || '';
  }

  // 통계 관련 메서드들
  async getStatistics(period: string = '30d'): Promise<any> {
    try {
      const days = this.parsePeriodToDays(period);
      const startDate = new Date();
      startDate.setDate(startDate.getDate() - days);

      // 전체 통계
      const totalUsers = await this.dataSource.query(
        'SELECT COUNT(*) FROM users',
      );
      const totalRooms = await this.dataSource.query(
        'SELECT COUNT(*) FROM room',
      );
      const totalReservations = await this.dataSource.query(
        'SELECT COUNT(*) FROM reservation',
      );
      const activeReservations = await this.dataSource.query(
        `SELECT COUNT(*) FROM reservation WHERE reservation_starttime > NOW()`,
      );

      // 성장률 계산
      const userGrowth = await this.calculateGrowthRate('users', days);
      const reservationGrowth = await this.calculateGrowthRate(
        'reservation',
        days,
      );

      // 예약 상태별 통계 (status 필드 제거됨 - 빈 결과 반환)
      const reservationsByStatus = [];

      // 월별 예약 추이
      const monthlyReservations = await this.dataSource.query(
        `
        SELECT
          TO_CHAR(reservation_createdat, 'YYYY-MM') as month,
          COUNT(*) as count
        FROM reservation
        WHERE reservation_createdat >= $1
        GROUP BY TO_CHAR(reservation_createdat, 'YYYY-MM')
        ORDER BY month DESC
        LIMIT 6
      `,
        [startDate],
      );

      // 회의실별 이용률
      const roomStats = await this.dataSource.query(
        `
        SELECT
          r.room_name as room_name,
          COUNT(res.reservation_id) as reservation_count,
          ROUND(COUNT(res.reservation_id) * 100.0 / GREATEST(1, $1), 2) as utilization
        FROM room r
        LEFT JOIN reservation res ON r.room_id = res.room_id
          AND res.reservation_createdat >= $2
        GROUP BY r.room_id, r.room_name
        ORDER BY reservation_count DESC
      `,
        [days, startDate],
      );

      // 시간대별 예약 현황
      const hourlyStats = await this.dataSource.query(
        `
        SELECT
          EXTRACT(HOUR FROM reservation_starttime) as hour,
          COUNT(*) as count
        FROM reservation
        WHERE reservation_createdat >= $1
        GROUP BY EXTRACT(HOUR FROM reservation_starttime)
        ORDER BY hour
      `,
        [startDate],
      );

      // 활발한 사용자
      const topUsers = await this.dataSource.query(
        `
        SELECT
          u.user_name as login,
          u.user_name as displayName,
          COUNT(r.reservation_id) as reservation_count
        FROM users u
        LEFT JOIN reservation r ON u.user_id = r.user_id
          AND r.reservation_createdat >= $1
        GROUP BY u.user_id, u.user_name
        ORDER BY reservation_count DESC
        LIMIT 5
      `,
        [startDate],
      );

      // 사용자 등록 추이
      const userRegistrationTrend = await this.dataSource.query(
        `
        SELECT
          TO_CHAR(user_createdat, 'YYYY-MM') as month,
          COUNT(*) as count
        FROM users
        WHERE user_createdat >= $1
        GROUP BY TO_CHAR(user_createdat, 'YYYY-MM')
        ORDER BY month DESC
        LIMIT 6
      `,
        [startDate],
      );

      return {
        overview: {
          totalUsers: parseInt(totalUsers[0].count),
          totalRooms: parseInt(totalRooms[0].count),
          totalReservations: parseInt(totalReservations[0].count),
          activeReservations: parseInt(activeReservations[0].count),
          userGrowth: userGrowth,
          reservationGrowth: reservationGrowth,
        },
        reservationStats: {
          byStatus: {
            confirmed: 0,
            cancelled: 0,
            completed: 0,
          },
          byMonth: monthlyReservations.map((m) => ({
            month: this.formatMonth(m.month),
            count: parseInt(m.count),
            growth: 0, // 계산 로직 추가 가능
          })),
          byRoom: roomStats.map((r) => ({
            roomName: r.room_name,
            count: parseInt(r.reservation_count),
            utilization: parseFloat(r.utilization),
          })),
          byHour: hourlyStats.map((h) => ({
            hour: parseInt(h.hour),
            count: parseInt(h.count),
          })),
        },
        userStats: {
          activeUsers: parseInt(totalUsers[0].count), // 활성 사용자 로직 추가 가능
          newUsersThisMonth: 0, // 이번 달 신규 사용자 계산 로직 추가
          topUsers: topUsers.map((u) => ({
            login: u.login,
            displayName: u.displayName,
            reservationCount: parseInt(u.reservation_count),
          })),
          registrationTrend: userRegistrationTrend.map((u) => ({
            month: this.formatMonth(u.month),
            count: parseInt(u.count),
          })),
        },
        systemStats: {
          averageSessionDuration: 45, // 실제 세션 분석 로직 추가 가능
          peakUsageHour: 15, // 피크 시간 계산
          systemUptime: 99.8, // 시스템 가동률
          errorRate: 0.2, // 에러율
        },
      };
    } catch (error) {
      console.error('Failed to get statistics:', error);
      // 기본 mock 데이터 반환
      return this.getMockStatistics();
    }
  }

  async exportStatistics(): Promise<Buffer> {
    try {
      const statistics = await this.getStatistics('30d');

      // 전체 통계 시트
      const overviewData = [
        ['항목', '값'],
        ['총 사용자', statistics.overview.totalUsers],
        ['총 회의실', statistics.overview.totalRooms],
        ['총 예약', statistics.overview.totalReservations],
        ['활성 예약', statistics.overview.activeReservations],
        ['사용자 증가율', `${statistics.overview.userGrowth}%`],
        ['예약 증가율', `${statistics.overview.reservationGrowth}%`],
      ];

      // 회의실별 이용률 시트
      const roomData = [
        ['회의실명', '예약 수', '이용률(%)'],
        ...statistics.reservationStats.byRoom.map((room) => [
          room.roomName,
          room.count,
          room.utilization,
        ]),
      ];

      // 활발한 사용자 시트
      const usersData = [
        ['로그인 ID', '이름', '예약 수'],
        ...statistics.userStats.topUsers.map((user) => [
          user.login,
          user.displayName || '',
          user.reservationCount,
        ]),
      ];

      // 월별 예약 추이 시트
      const monthlyData = [
        ['월', '예약 수'],
        ...statistics.reservationStats.byMonth.map((month) => [
          month.month,
          month.count,
        ]),
      ];

      // 워크북 생성
      const workbook = XLSX.utils.book_new();

      // 시트 추가
      const overviewSheet = XLSX.utils.aoa_to_sheet(overviewData);
      const roomSheet = XLSX.utils.aoa_to_sheet(roomData);
      const usersSheet = XLSX.utils.aoa_to_sheet(usersData);
      const monthlySheet = XLSX.utils.aoa_to_sheet(monthlyData);

      XLSX.utils.book_append_sheet(workbook, overviewSheet, '전체 통계');
      XLSX.utils.book_append_sheet(workbook, roomSheet, '회의실별 이용률');
      XLSX.utils.book_append_sheet(workbook, usersSheet, '활발한 사용자');
      XLSX.utils.book_append_sheet(workbook, monthlySheet, '월별 예약 추이');

      return Buffer.from(
        XLSX.write(workbook, { type: 'buffer', bookType: 'xlsx' }),
      );
    } catch (error) {
      console.error('Failed to export statistics:', error);
      throw error;
    }
  }

  private parsePeriodToDays(period: string): number {
    switch (period) {
      case '7d':
        return 7;
      case '30d':
        return 30;
      case '90d':
        return 90;
      case '1y':
        return 365;
      default:
        return 30;
    }
  }

  private async calculateGrowthRate(
    table: string,
    days: number,
  ): Promise<number> {
    try {
      // Whitelist allowed tables to prevent SQL injection
      const allowedTables: { [key: string]: string } = {
        'users': 'user_createdat',
        'reservation': 'reservation_createdat',
      };

      if (!allowedTables[table]) {
        throw new Error(`Invalid table name: ${table}`);
      }

      const createdAtColumn = allowedTables[table];

      const currentPeriod = new Date();
      currentPeriod.setDate(currentPeriod.getDate() - days);

      const previousPeriod = new Date();
      previousPeriod.setDate(previousPeriod.getDate() - days * 2);

      const currentCount = await this.dataSource.query(
        `SELECT COUNT(*) FROM ${table} WHERE ${createdAtColumn} >= $1`,
        [currentPeriod],
      );

      const previousCount = await this.dataSource.query(
        `SELECT COUNT(*) FROM ${table} WHERE ${createdAtColumn} >= $1 AND ${createdAtColumn} < $2`,
        [previousPeriod, currentPeriod],
      );

      const current = parseInt(currentCount[0].count);
      const previous = parseInt(previousCount[0].count);

      if (previous === 0) return current > 0 ? 100 : 0;
      return Math.round(((current - previous) / previous) * 100 * 100) / 100;
    } catch (error) {
      console.error('Failed to calculate growth rate:', error);
      return 0;
    }
  }

  private formatMonth(monthStr: string): string {
    const [year, month] = monthStr.split('-');
    return `${parseInt(month)}월`;
  }

  private getMockStatistics(): any {
    return {
      overview: {
        totalUsers: 156,
        totalRooms: 12,
        totalReservations: 342,
        activeReservations: 24,
        userGrowth: 12.5,
        reservationGrowth: 8.3,
      },
      reservationStats: {
        byStatus: {
          confirmed: 24,
          cancelled: 8,
          completed: 310,
        },
        byMonth: [
          { month: '6월', count: 55, growth: 9.1 },
          { month: '5월', count: 48, growth: 7.3 },
          { month: '4월', count: 41, growth: -8.2 },
          { month: '3월', count: 52, growth: 12.8 },
          { month: '2월', count: 38, growth: -2.1 },
          { month: '1월', count: 45, growth: 5.2 },
        ],
        byRoom: [
          { roomName: '대회의실 A', count: 85, utilization: 78.5 },
          { roomName: '소회의실 B', count: 62, utilization: 65.2 },
          { roomName: '프로젝트룸 C', count: 48, utilization: 52.3 },
          { roomName: '스터디룸 D', count: 35, utilization: 41.8 },
          { roomName: '세미나실', count: 28, utilization: 38.9 },
        ],
        byHour: [
          { hour: 9, count: 15 },
          { hour: 10, count: 25 },
          { hour: 11, count: 32 },
          { hour: 12, count: 8 },
          { hour: 13, count: 12 },
          { hour: 14, count: 28 },
          { hour: 15, count: 35 },
          { hour: 16, count: 30 },
          { hour: 17, count: 18 },
          { hour: 18, count: 10 },
        ],
      },
      userStats: {
        activeUsers: 134,
        newUsersThisMonth: 18,
        topUsers: [
          { login: 'yutsong', displayName: '유영재', reservationCount: 15 },
          { login: 'jskim', displayName: '김진수', reservationCount: 12 },
          { login: 'hpark', displayName: '박현우', reservationCount: 11 },
          { login: 'slee', displayName: '이승현', reservationCount: 9 },
          { login: 'mkim', displayName: '김민지', reservationCount: 8 },
        ],
        registrationTrend: [
          { month: '6월', count: 18 },
          { month: '5월', count: 28 },
          { month: '4월', count: 21 },
          { month: '3월', count: 32 },
          { month: '2월', count: 18 },
          { month: '1월', count: 25 },
        ],
      },
      systemStats: {
        averageSessionDuration: 45,
        peakUsageHour: 15,
        systemUptime: 99.8,
        errorRate: 0.2,
      },
    };
  }

  // 위험한 시스템 작업들
  async resetDatabase(): Promise<void> {
    console.warn(
      '⚠️ DATABASE RESET REQUESTED - This is a dangerous operation!',
    );

    // 실제 운영환경에서는 이 기능을 비활성화하거나 추가 보안 검증을 해야 합니다
    if (process.env.NODE_ENV === 'production') {
      throw new Error(
        'Database reset is not allowed in production environment',
      );
    }

    try {
      // 모든 테이블의 데이터를 삭제 (구조는 유지)
      await this.dataSource.query(
        'TRUNCATE TABLE reservation RESTART IDENTITY CASCADE',
      );
      await this.dataSource.query(
        'TRUNCATE TABLE room RESTART IDENTITY CASCADE',
      );
      await this.dataSource.query(
        'TRUNCATE TABLE users RESTART IDENTITY CASCADE',
      );
      await this.dataSource.query(
        'TRUNCATE TABLE system_settings RESTART IDENTITY CASCADE',
      );

      console.log('✅ Database reset completed');
    } catch (error) {
      console.error('❌ Database reset failed:', error);
      throw new Error('Failed to reset database: ' + error.message);
    }
  }

  async clearLogs(): Promise<void> {
    console.log('🧹 Clearing log files...');

    try {
      const fs = require('fs');
      const path = require('path');

      // 로그 디렉토리 경로들
      const logPaths = [
        path.join(process.cwd(), 'logs'),
        path.join(process.cwd(), 'log.txt'),
        '/var/log/42erp', // 시스템 로그 경로 (실제 환경에 맞게 조정)
      ];

      for (const logPath of logPaths) {
        try {
          if (fs.existsSync(logPath)) {
            const stat = fs.statSync(logPath);

            if (stat.isDirectory()) {
              // 디렉토리인 경우 모든 파일 삭제
              const files = fs.readdirSync(logPath);
              for (const file of files) {
                const filePath = path.join(logPath, file);
                fs.unlinkSync(filePath);
                console.log(`Deleted log file: ${filePath}`);
              }
            } else {
              // 파일인 경우 직접 삭제
              fs.unlinkSync(logPath);
              console.log(`Deleted log file: ${logPath}`);
            }
          }
        } catch (error) {
          console.warn(`Failed to delete ${logPath}:`, error.message);
        }
      }

      console.log('✅ Log files cleared');
    } catch (error) {
      console.error('❌ Failed to clear logs:', error);
      throw new Error('Failed to clear logs: ' + error.message);
    }
  }

  async testApiKeys(): Promise<any> {
    console.log('🔧 Testing API keys...');

    const results = {
      api42: false,
      email: false,
    };

    try {
      // 42 API 테스트
      const clientId = process.env.FORTYTWO_CLIENT_ID;
      const clientSecret = process.env.FORTYTWO_CLIENT_SECRET;

      if (clientId && clientSecret) {
        // 간단한 42 API 연결 테스트 (토큰 없이 public endpoint 호출)
        try {
          const response = await fetch('https://api.intra.42.fr/oauth/token', {
            method: 'POST',
            headers: {
              'Content-Type': 'application/json',
            },
            body: JSON.stringify({
              grant_type: 'client_credentials',
              client_id: clientId,
              client_secret: clientSecret,
            }),
          });

          if (response.status === 200) {
            results.api42 = true;
            console.log('✅ 42 API connection test passed');
          } else {
            console.log('❌ 42 API connection test failed:', response.status);
          }
        } catch (error) {
          console.log('❌ 42 API connection test error:', error.message);
        }
      } else {
        console.log('⚠️ 42 API credentials not configured');
      }

      // 이메일 API 테스트 (SMTP 또는 SendGrid)
      const emailApiKey = process.env.EMAIL_API_KEY;
      const smtpHost = process.env.SMTP_HOST;

      if (emailApiKey || smtpHost) {
        // 실제 이메일 발송 없이 설정 유효성만 검증
        try {
          // 이메일 설정이 있다고 가정하고 true로 설정
          // 실제 환경에서는 SMTP 연결 테스트나 API 호출을 수행
          results.email = true;
          console.log('✅ Email API configuration found');
        } catch (error) {
          console.log('❌ Email API test error:', error.message);
        }
      } else {
        console.log('⚠️ Email API credentials not configured');
      }
    } catch (error) {
      console.error('❌ API key tests failed:', error);
    }

    console.log('🔧 API key test results:', results);
    return results;
  }

  // 활동 로그 관련 메서드들
  async logActivity(
    type: ActivityType,
    title: string,
    description?: string,
    userId?: number,
    metadata?: any,
    level: 'info' | 'success' | 'warning' | 'error' = 'info',
  ): Promise<void> {
    try {
      const activityLog = this.activityLogRepository.create({
        type,
        title,
        description,
        userId,
        metadata,
        level,
      });
      await this.activityLogRepository.save(activityLog);
    } catch (error) {
      console.error('Failed to log activity:', error);
    }
  }

  async getRecentActivities(limit: number = 10): Promise<ActivityLog[]> {
    try {
      return await this.activityLogRepository.find({
        relations: ['user'],
        order: { createdAt: 'DESC' },
        take: limit,
      });
    } catch (error) {
      console.error('Failed to get recent activities:', error);
      return [];
    }
  }

  async getActivitiesByType(
    type: ActivityType,
    limit: number = 10,
  ): Promise<ActivityLog[]> {
    try {
      return await this.activityLogRepository.find({
        where: { type },
        relations: ['user'],
        order: { createdAt: 'DESC' },
        take: limit,
      });
    } catch (error) {
      console.error('Failed to get activities by type:', error);
      return [];
    }
  }

  async clearOldActivities(daysOld: number = 30): Promise<void> {
    try {
      const cutoffDate = new Date();
      cutoffDate.setDate(cutoffDate.getDate() - daysOld);

      await this.activityLogRepository
        .createQueryBuilder()
        .delete()
        .where('createdAt < :cutoffDate', { cutoffDate })
        .execute();

      console.log(`Cleared activity logs older than ${daysOld} days`);
    } catch (error) {
      console.error('Failed to clear old activities:', error);
    }
  }

  async createSampleActivities(): Promise<void> {
    try {
      const now = new Date();

      const sampleActivities = [
        {
          type: ActivityType.ROOM_CREATED,
          title: '새 회의실 추가됨',
          description: "관리자에 의해 '대회의실 C' 추가",
          level: 'success' as const,
          createdAt: new Date(now.getTime() - 5 * 60 * 1000), // 5분 전
        },
        {
          type: ActivityType.EXCEL_UPLOAD,
          title: 'Excel 데이터 업로드',
          description: '15개 회의실 정보 일괄 업데이트',
          level: 'info' as const,
          createdAt: new Date(now.getTime() - 60 * 60 * 1000), // 1시간 전
        },
        {
          type: ActivityType.BACKUP_CREATED,
          title: '시스템 백업 완료',
          description: '자동 백업이 성공적으로 완료됨',
          level: 'success' as const,
          createdAt: new Date(now.getTime() - 3 * 60 * 60 * 1000), // 3시간 전
        },
        {
          type: ActivityType.USER_REGISTERED,
          title: '새 사용자 등록',
          description: '새로운 사용자가 시스템에 등록되었습니다',
          level: 'info' as const,
          createdAt: new Date(now.getTime() - 6 * 60 * 60 * 1000), // 6시간 전
        },
        {
          type: ActivityType.SETTINGS_UPDATED,
          title: '시스템 설정 변경',
          description: '예약 정책이 업데이트되었습니다',
          level: 'info' as const,
          createdAt: new Date(now.getTime() - 12 * 60 * 60 * 1000), // 12시간 전
        },
      ];

      for (const activity of sampleActivities) {
        // 중복 방지를 위해 기존 활동 확인
        const existing = await this.activityLogRepository.findOne({
          where: {
            title: activity.title,
            description: activity.description,
          },
        });

        if (!existing) {
          const activityLog = this.activityLogRepository.create(activity);
          await this.activityLogRepository.save(activityLog);
        }
      }

      console.log('Sample activities created successfully');
    } catch (error) {
      console.error('Failed to create sample activities:', error);
    }
  }

}
